# Welcome to Jekyll!
#

# Site settings
title: Lilinku Tiga Putra
description: |
  Memiliki usaha sendiri adalah impian semua orang.  
  Oleh karena itu kami ingin membantu Anda untuk memiliki bisnis pembuatan lilin.  
owner: Daniel Aditya Istyana # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: lilinku@adityadaniel.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lilinku.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/3putralilinku
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://www.facebook.com/Lilin-Tiga-Putra-426361030907654/
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
